### ISSUE TITLE
hdajackretask documentation window takes up all screens

### ISSUE THREAD

**Issue by francisdb** [alsa-project/alsa-tools#20]
For a multi-monitor setup you get a very large window.

The code below should probably be removed

https://github.com/alsa-project/alsa-tools/blob/8c8d6941f21ea68894ce7fd13e92b3ac9f16dc8a/hdajackretask/main-gtk.c#L517-L523

**Comment by tiwai** [comment]
If the intention of the code is rather to reduce the size not to overflow the screen, we can add the check to compare with the current size, and apply it only when the new size is smaller than the current size, instead?

**Comment by francisdb** [comment]
I think a fixed size would be ok, the user can always resize.

This is what currently happens (gnome wayland)
![image](https://github.com/alsa-project/alsa-tools/assets/161305/f43d814d-a1c9-4af8-b4b2-e19f9f5dccc5)

**Comment by tiwai** [comment]
We should check the behavior of small screen, too. If the code there was intended to avoid the overflow of the small screen, dropping the whole code will break in other way for such a system.

**Comment by perexg** [comment]
It's really true for the multi-monitor system with several screens. I pushed a 1600x1000 limit. There is no much text for the bigger window and those values are safe for most monitors, I think.
