### ISSUE TITLE
hdajackretask /sys/class/sound/hwC1D0/reconfig Device or resource busy

### ISSUE THREAD

**Issue by ShalokShalom** [alsa-project/alsa-tools#21]
I try to apply the settings within _hdajackretask_ and then get this: 

![Screenshot_20231111_103300](https://github.com/alsa-project/alsa-tools/assets/6344099/51f8254a-c9a8-4ce7-9048-e537843d4653)

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.0, NixOS, 23.05 (Stoat), 23.05.4662.34bdaaf1f0b7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.6`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by perexg** [comment]
All applications using the sound hardware must be suspended before applying of new config. It's not a fault of this utility.
