### ISSUE TITLE
Missing macro 'AM_PATH_LD10K1' not found in library

### ISSUE THREAD

**Issue by ronohara** [alsa-project/alsa-tools#7]
New Linux Mint 20.0 install (Ubuntu 20.04 based) on HP X360 with TigerLake hardware.

This distro only has lib-alsa-1.2.2   ... so I need to compile/install the latest alsa stuff from source

I have the kernel working at seeing the hardware - in the mainline 5.13 kernel it is already available. Installed the firmware and UCM2 stuff.  'speaker-test' works ... lots of details in this closed bug: https://github.com/thesofproject/linux/issues/2700#issuecomment-854033711

Installed alsa-lib from source, and alsa-utils .... but compiling alsa-tools (gitcompile) fails.  This macro needs to be installed, but I am wondering what the best way is ...?

make[3]: Leaving directory '/root/alsa-1.2.5/alsa-tools-1.2.5/ld10k1/src'
make[3]: Entering directory '/root/alsa-1.2.5/alsa-tools-1.2.5/ld10k1'
sed -e 's,[@]sbindir[@],/usr/local/sbin,g' -e 's,[@]binarydir[@],/usr/local/bin,g' -e 's,[@]sysconfdir[@],/usr/local/etc,g' ./ld10k1d.in > ld10k1d
make[3]: Leaving directory '/root/alsa-1.2.5/alsa-tools-1.2.5/ld10k1'
make[2]: Leaving directory '/root/alsa-1.2.5/alsa-tools-1.2.5/ld10k1'
make[1]: Leaving directory '/root/alsa-1.2.5/alsa-tools-1.2.5/ld10k1'
make[1]: Entering directory '/root/alsa-1.2.5/alsa-tools-1.2.5/ld10k1'
make  all-recursive
make[2]: Entering directory '/root/alsa-1.2.5/alsa-tools-1.2.5/ld10k1'
Making all in setup
make[3]: Entering directory '/root/alsa-1.2.5/alsa-tools-1.2.5/ld10k1/setup'
Making all in effects
make[4]: Entering directory '/root/alsa-1.2.5/alsa-tools-1.2.5/ld10k1/setup/effects'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/root/alsa-1.2.5/alsa-tools-1.2.5/ld10k1/setup/effects'
make[4]: Entering directory '/root/alsa-1.2.5/alsa-tools-1.2.5/ld10k1/setup'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/root/alsa-1.2.5/alsa-tools-1.2.5/ld10k1/setup'
make[3]: Leaving directory '/root/alsa-1.2.5/alsa-tools-1.2.5/ld10k1/setup'
Making all in doc
make[3]: Entering directory '/root/alsa-1.2.5/alsa-tools-1.2.5/ld10k1/doc'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/root/alsa-1.2.5/alsa-tools-1.2.5/ld10k1/doc'
Making all in patch
make[3]: Entering directory '/root/alsa-1.2.5/alsa-tools-1.2.5/ld10k1/patch'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/root/alsa-1.2.5/alsa-tools-1.2.5/ld10k1/patch'
Making all in dump
make[3]: Entering directory '/root/alsa-1.2.5/alsa-tools-1.2.5/ld10k1/dump'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/root/alsa-1.2.5/alsa-tools-1.2.5/ld10k1/dump'
Making all in contrib
make[3]: Entering directory '/root/alsa-1.2.5/alsa-tools-1.2.5/ld10k1/contrib'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/root/alsa-1.2.5/alsa-tools-1.2.5/ld10k1/contrib'
Making all in include
make[3]: Entering directory '/root/alsa-1.2.5/alsa-tools-1.2.5/ld10k1/include'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/root/alsa-1.2.5/alsa-tools-1.2.5/ld10k1/include'
Making all in src
make[3]: Entering directory '/root/alsa-1.2.5/alsa-tools-1.2.5/ld10k1/src'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/root/alsa-1.2.5/alsa-tools-1.2.5/ld10k1/src'
make[3]: Entering directory '/root/alsa-1.2.5/alsa-tools-1.2.5/ld10k1'
make[3]: Leaving directory '/root/alsa-1.2.5/alsa-tools-1.2.5/ld10k1'
make[2]: Leaving directory '/root/alsa-1.2.5/alsa-tools-1.2.5/ld10k1'
make[1]: Leaving directory '/root/alsa-1.2.5/alsa-tools-1.2.5/ld10k1'
./qlo10k1
configure.ac:21: warning: macro 'AM_PATH_LD10K1' not found in library
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
configure.ac:21: warning: macro 'AM_PATH_LD10K1' not found in library
configure.ac:21: error: possibly undefined macro: AM_PATH_LD10K1
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
make: *** [Makefile:9: all] Error 1

**Comment by hottwaj** [comment]
Hey, I hit the same issue - also trying to compile on LM20 this for a HP 14 Tiger Lake :) 

Looking at https://github.com/alsa-project/alsa-tools/blob/3e4fd7dffbf40b2997075320ce24aaae1b97f328/ld10k1/ld10k1.m4

That macro is used to determine whether iblo10k1 is present.  You can get it on LM20 using ```sudo apt install iblo10k1-dev```

I think hit another compilation issue with needing to set `QTDIR` which I've not yet figured out...

**Comment by hottwaj** [comment]
I see that in the Debian package, the subprogram `qlo10k1` is not being built since ~2012 as it depends on qt3 which is not packaged for Debian/ubuntu/LM anymore
https://salsa.debian.org/alsa-team/alsa-tools/-/commit/321631cb5a19b36f5f8b1a666779a8ebca83efc3

If you remove ```ld10k1 qlo10k1``` from the Makefile before building (as the Debian team have done), then everything compiles fine.

**Comment by ronohara** [comment]
@hottwaj ..... thanks - removing ld10k1 and qlo10k1 did the trick.

**Comment by hottwaj** [comment]
@ronohara did you find you could get sound working from a cold boot on your Hp 14 tiger lake once this was installed? I've got Lm20, 5.13 kernel with soundwire switched on, alsa-lib & co all at v1.2.5, but still no sound... Do I need alsa etc at 1.2.5.1? Or maybe there is something else tied to ubuntu 20.04 that is stopping it  all from working...

**Comment by ronohara** [comment]
I have been told I need alsa @ 1.2.5  ... and you need to remove the existing alsa using apt  (apt remove alsa-lib and the alsa-topology-cont too) before you compile from source ... otherwise ot links the wrong topology file.
That said, I still don't have it working ... I will update https://github.com/thesofproject/linux/issues/2700#issuecomment-854033711
