### ISSUE TITLE
vxloader: no VX-compatible cards found VX222v2

### ISSUE THREAD

**Issue by LGCW** [alsa-project/alsa-tools#9]
I have an AMD AM4 motherboard with two legacy PCI slots. The bridge uses the ASMedia ASM1083. Running vxloader produces the following error. 

```
vxloader 
vxloader: no VX-compatible cards found

vxloader -D hw:0
vxloader: cannot open hwdep hw:0
```
If it's anything like the 9632 the firmware has to be loaded in order to function?  Best I can tell Debian 11 sees the card. 

```
lsmod | grep vx
snd_vx222              24576  0
snd_vx_lib             57344  1 snd_vx222
snd_pcm               147456  2 snd_hdsp,snd_vx_lib
snd                   110592  8 snd_seq_device,snd_hwdep,snd_hdsp,snd_timer,snd_vx_lib,snd_vx222,snd_pcm,snd_rawmidi
```

```
cat /proc/asound/card0/vx-status
Digigram VX222/v2 at 0xf100 & 0xf000, irq 25
Xilinx Firmware: Loaded
Device Initialized: Yes
DSP audio info: realtime linear8 linear16 linear24
Input Source: Analog
Clock Mode: Internal
Clock Source: Internal
Frequency: 48000
Detected Frequency: 0
Detected UER type: Not Present
Min/Max/Cur IBL: 252/2016/252 (granularity=126)
```
I noticed hdsploader picked it up as well.  
```
hdsploader 
hdsploader - firmware loader for RME Hammerfall DSP cards
Looking for HDSP + Multiface or Digiface cards :
Card 0 : Digigram VX222/v2 at 0xf100 & 0xf000, irq 25
Card 1 : RME Hammerfall HDSP 9632 at 0xf7400000, irq 27
```

**Comment by tiwai** [comment]
vxloader isn't needed and won't run on the recent kernels that have already the firmware support.
It's simply superfluous.

**Comment by LGCW** [comment]
Good to know. I had hoped that was the culprit. 

I managed to get the VX222v2 to record  / playback with audacity but that's about it. Crashes if anything is adjusted with alsamixer. 

Any attempt with a DAW (Reaper/Mixbus/Ardour) using ALSA Freezes the system. Jack1 & 2 error out. 

I'll put it on the knackered list on the site. 

Thanks for your time, 
Venn
